*-----------------------------------------------------------------------------
* <Rating>-67</Rating>
*-----------------------------------------------------------------------------
    PROGRAM TEST.PRG


*-----------------------------------------------------------------------------
*
*-----------------------------------------------------------------------------
* Modification History :
*-----------------------------------------------------------------------------

    $INSERT I_F.ACCOUNT
    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_F.TELLER
    $INSERT I_F.ACCOUNT
    $INSERT I_F.TELLER.FINANCIAL.SERVICES
    $INSERT I_F.EB.SLV.CTA.SIMPLIFICADA.TXN
    $INSERT I_F.EB.SLV.GLOBAL.PARAM
    $INSERT I_F.AA.ACCOUNT
    $INSERT I_F.AA.ARRANGEMENT
    $INSERT I_F.DISPO.ITEMS
    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_ENQUIRY.COMMON

*-----------------------------------------------------------------------------

    IF(PUTENV("OFS_SOURCE=SLVOFSPS")) THEN
    CRT "OK"
    END
* ft: ft+5números de fecha que es un entero de viene de 1914 a la fecha+random
*10000000821371,AA19024Y175G
    CALL JF.INITIALISE.CONNECTION
*CALL SLV.ENVIO.MENSAJES.HDM('79194550','MONEDAZUL PRUEBA MSJ')
CALL SLV.B.DELETE.USER.HID

*    GOSUB PRUEBA.IF
*   GOSUB DESENCRIPTAR
*    GOSUB NUEVO.TOKEN
*    CALL SLV.E.STM.INFO.PE('')
*GOSUB INIT
*GOSUB CONSULTAR.CUENTA
    RETURN

INIT:
    FN.CUS.AC			='F.CUSTOMER.ACCOUNT'
    F.CUS.AC			=''
    CALL OPF(FN.CUS.AC, F.CUS.AC)
    RETURN


PRUEBA.IF:
AAA=1

IF AAA EQ '2' THEN
PRINT 'AAA=2'
END
ELSE
PRINT 'AAA NE 2'
END

IF AAA EQ '1' THEN
PRINT 'AAA=1'
END

ELSE
PRINT 'AAA NE 1'
END

RETURN


*
*    CONSULTAR.CUENTA:
*CUSTOMER='158820'
*    CALL F.READ(FN.CUS.AC,CUSTOMER, R.CUS.AC, F.CUS.AC, F.ERR.CUS.AC)
*    ;*NUMERO=COUNT(R.CUS.AC,VM)
*    IF R.CUS.AC THEN
*    NUMERO1=COUNT(R.CUS.AC,VM)
*    NUMERO2=COUNT(R.CUS.AC,FM)
*    NUMERO=NUMERO+1
*    FOR j=1 TO NUMERO
*        CUENTA.N= FIELD(R.CUS.AC,FM,j)
*
*        CALL F.READ(FN.ACC, CUENTA.N, R.ACCOUNT, F.ACC, Y.ERR.AC)
*        CATEGORY=R.ACCOUNT<AC.CATEGORY>
*
*        IF CATEGORY EQ CATEGORY.SIMP THEN
*            ARRANGEMENT=R.ACCOUNT<AC.ARRANGEMENT.ID>
*
*        END
*    NEXT
*
*    END
*
*    RETURN

*    ENCRIPTAR:
*
*    Y.SEEDS  = '79194550' : @VM : '045627986':@VM
*    Y.SEEDS := '20200127' : @VM :'12304927'
*    CALL SLV.UTIL.STM.TOKEN('STM', Y.SEEDS, Y.TOKEN, Y.ERROR)
*    TOKEN=Y.TOKEN
*    CRT Y.TOKEN
*    RETURN
*
*    DESENCRIPTAR:
*		Y.TOKEN = FIELD(TOKEN, @VM, 1)
*		Y.HORA = FIELD(TOKEN, @VM, 2)
*		Y.CEL1 = SUBSTRINGS(Y.S1,1,1)
*		Y.CEL2 = SUBSTRINGS(Y.S1,2,1)
*		Y.CEL3 = SUBSTRINGS(Y.S1,3,1)
*		Y.CEL4 = SUBSTRINGS(Y.S1,4,1)
*		Y.CEL5 = SUBSTRINGS(Y.S1,5,1)
*		Y.CEL6 = SUBSTRINGS(Y.S1,6,1)
*		Y.CEL7 = SUBSTRINGS(Y.S1,7,1)
*		Y.CEL8 = SUBSTRINGS(Y.S1,8,1)
*		Y.TOKEN.NEW = SUBSTRINGS(Y.TOKEN,4,4)
*		Y.TOKEN1 = SUBSTRINGS(Y.TOKEN.NEW,1,1)
*		Y.TOKEN2 = SUBSTRINGS(Y.TOKEN.NEW,2,1)
*		Y.TOKEN3 = SUBSTRINGS(Y.TOKEN.NEW,3,1)
*		Y.TOKEN4 = SUBSTRINGS(Y.TOKEN.NEW,4,1)
*		Y.TOKEN.CEL = Y.ORIGEN:Y.TOKEN3:Y.CEL8:Y.CEL3:Y.TOKEN1:Y.CEL7:Y.CEL2:Y.TOKEN4:Y.CEL5:Y.CEL1:Y.TOKEN2:Y.CEL6:Y.CEL4
*		TOKEN = Y.TOKEN.CEL:@VM:Y.HORA
*		TOKEN='1706192387416'
*		TOKEN.NUEVO=FIELD(TOKEN, @VM, 1)
*		ORIGEN=SUBSTRINGS(TOKEN.NUEVO,1,1)
*		TOKEN3=SUBSTRINGS(TOKEN.NUEVO,2,1)
*		CEL8=SUBSTRINGS(TOKEN.NUEVO,3,1)
*		CEL3=SUBSTRINGS(TOKEN.NUEVO,4,1)
*		TOKEN1=SUBSTRINGS(TOKEN.NUEVO,5,1)
*		CEL7=SUBSTRINGS(TOKEN.NUEVO,6,1)
*		CEL2=SUBSTRINGS(TOKEN.NUEVO,7,1)
*		TOKEN4=SUBSTRINGS(TOKEN.NUEVO,8,1)
*		CEL5=SUBSTRINGS(TOKEN.NUEVO,9,1)
*		CEL1=SUBSTRINGS(TOKEN.NUEVO,10,1)
*		TOKEN2=SUBSTRINGS(TOKEN.NUEVO,11,1)
*		CEL6=SUBSTRINGS(TOKEN.NUEVO,12,1)
*		CEL4=SUBSTRINGS(TOKEN.NUEVO,13,1)
*
*		TELEFONO=CEL1:CEL2:CEL3:CEL4:CEL5:CEL6:CEL7:CEL8
*		CRT TELEFONO
*
*RETURN


CONSULTAR.HISTORICO:
    CUSTOMER ='158821'
    FN.DISPO.ITEMS.H = "F.DISPO.ITEMS$HIS"
    F.DISPO.ITEMS.H = ""
    FN.DISPO.ITEMS = "F.DISPO.ITEMS"
    F.DISPO.ITEMS = ""
    CALL OPF(FN.DISPO.ITEMS,F.DISPO.ITEMS)
    CALL OPF(FN.DISPO.ITEMS.H,F.DISPO.ITEMS.H)

    SELECT.DISP.H = "SELECT ": FN.DISPO.ITEMS.H:" WITH @ID LIKE '%":CUSTOMER:"%'"
    SELECT.CMD = "SELECT ":FN.DISPO.ITEMS.H:" WITH EVENT.REFERENCE EQ '":CUSTOMER:"'"
    CALL EB.READLIST(SELECT.DISP.H, LIST.CUST, '', NO.OF.CUST, ERR.CUST)
 ;*   CALL EB.READLIST(SELECT.CMD, LIST.CUST2, '', NO.OF.CUST2, ERR.CUST2)

        CUSTOMERH='158821*BNK'
        CALL F.READ.HISTORY(FN.DISPO.ITEMS.H, CUSTOMERH, R.DISPO, F.DISPO.ITEMS.H, ERR.D)
        DISPO.STATUS=R.DISPO<DISP.ITM.DISPO.STATUS>
        NUMERO=DCOUNT(LIST.CUST,FM)

        FOR j=1 TO NUMERO
            CUSTOMERH= FIELD(LIST.CUST,FM,j)
            NUM.H= FIELD(CUSTOMERH,';',2)
        NEXT

        IF NUM.H GT 1 THEN
            ESCREENEADO='SI'
            CUSTOMERH='158820*BNK;1'
            CALL F.READ.HISTORY(FN.DISPO.ITEMS.H, CUSTOMERH, R.DISPO, F.DISPO.ITEMS.H, ERR.D)

            DISPO.STATUS=R.DISPO<DISP.ITM.DISPO.STATUS>
            AAERGT=ASDGAS

        END
        ELSE
        ESCREENEADO='NO'
    END


    RETURN
*
*  NUEVO.TOKEN:
*    Y.SEEDS  = '79194550' : @VM : '045627986'
*    Y.SEEDS := '20200218' : VM :'0710206'
*		Y.ERROR=''
*		CALL SLV.UTIL.STM.TOKEN('STM', Y.SEEDS, Y.TOKEN.VERIFI, Y.ERROR)
*		CRT Y.TOKEN.VERIFI
*  RETURN
*
*
*
*
*GENERAR.FT:
*YBASE.ID = ''
*YTYPE = 'F'
*FULL.FNAME = 'FBNK.FUNDS.TRANSFER'
*PGM.TYPE = '.IDA'
*ID.T = ''
*COMI = ''
*ID.N = '8'
*V$FUNCTION = 'I'
*CALL GET.NEXT.ID(YBASE.ID,YTYPE)
*FT.ID= COMI
*CRT FT.ID
*RETURN



