*-----------------------------------------------------------------------------
* <Rating>0</Rating>
*-----------------------------------------------------------------------------
    SUBROUTINE TEST.OFS2
    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_F.FUNDS.TRANSFER
    APP.NAME='FUNDS.TRANSFER'
    OFFUNCT='I'
    PROCESS='PROCESS'
    OFSVERSION='FUNDS.TRANSFER,'
    GTSMODE=''
    NO.OF.AUTH=0
    TRANSACTION.ID=''
    RECORD=''
    OFSRECORD=''
    RECORD<FT.TRANSACTION.TYPE>='AC'
    RECORD<FT.DEBIT.ACCT.NO>=10000000041449
    RECORD<FT.DEBIT.CURRENCY>='USD'
    RECORD<FT.DEBIT.AMOUNT>=1
    RECORD<FT.CREDIT.ACCT.NO>=10000000000165
    RECORD<FT.CREDIT.CURRENCY>='USD'
    CALL OFS.BUILD.RECORD(APP.NAME,OFSFUNCT,PROCESS,OFSVERSION,GTSMODE,NO.OF.AUTH,TRANSACTION.ID,RECORD,OFSRECORD)
    OFS.SRC = 'GENERIC.OFS.PROCESS'
    OFS.MSG.ID = ''
    OPTIONS = ''
    
    
    CRT 'OFSRECORD  :': OFSRECORD
    CALL OFS.POST.MESSAGE(OFSRECORD,OFS.MSG.ID,OFS.SRC,OPTIONS)
    CALL JOURNAL.UPDATE("")
    RETURN
END

